export enum EnvEnum {
  NODE_ENV,

  PORT,
  DEV_SERVER,
  STAGE_SERVER,
  MAIN_SERVER,

  //db
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_DATABASE,

  DATABASE_URL,
  REPLICA_DATABASE_URL,
  TEST_DATABASE_URL,

  //jwt
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET,

  //aws
  AWS_ACCESS_KEY,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_SIGNATURE_VERSION,
  AWS_S3_API_VERSION,
  AWS_S3_BUCKET,
  AWS_S3_GET_DURATION,
  AWS_S3_PUT_DURATION,

  //Firebase
  FIREBASE_TYPE,
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI,
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  FIREBASE_CLIENT_X509_CERT_URL,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,

  // SLACK
  SLACK_TOKEN,

  // OPEN AI
  OPENAI_API_KEY,
  OPENAI_ORGANIZATION_ID,
  OPENAI_CHAT_URL,

  // 프론트 URL
  FRONTEND_URL,

  // prompt
  CHATGPT_AI_KEYWORD_PROMPT,
  CHATGPT_RESUME_PROMPT,
  CHATGPT_SUMMARY_PROMPT,
  CHATGPT_SUMMARY_KEYWORD_PROMPT,
  CHATGPT_RECOMMEND_QUESTIONS_PROMPT,

  // redis key
  PROMPT_REDIS_KEY,
}
